apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: flask-ui
  namespace: flask
  labels:
    app: flask
    role: ui
spec:
  selector:
    matchLabels:
      app: flask
      role: ui
  replicas: 1
  template:
    metadata:
      labels:
        app: flask
        role: ui
        tier: frontend
    spec:
      containers:
      - name: flask-ui
        image: wonjin77/flask-ui:2.0
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: GET_HOSTS_FROM
          value: dns
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: flask-ui-service
  namespace: flask
spec:
  type: NodePort
  selector:
    app: flask
    role: ui
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 30500
